### ISSUE TITLE
can't add item (upload file ) on canvas course

### ISSUE THREAD

**Issue by thapakorn613** [ubc/docker-canvas#6]
I'm using docker, I try to upload file in Add Item to <NAMECOURSE>. 
An error occurred that "Failed to Create new Item" 
.
error from Console " POST http://10.110.3.110:8900/files_api?on_duplicate=rename 500 xhr.js:178 (Internal Server Error)"
.
and log on docker-canvas_app_i is "10.80.175.33 - - [15/Jul/2020:10:30:26 +0000] "POST /api/v1/folders/3/files HTTP/1.1" 200 835 "http://10.110.3.110:8900/courses/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Edg/83.0.478.61"
10.80.175.33 - - [15/Jul/2020:10:30:26 +0000] "POST /files_api?on_duplicate=rename HTTP/1.1" 500 94 "http://10.110.3.110:8900/courses/1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Edg/83.0.478.61"
"
.
Can help me?

**Comment by andrew-gardener** [comment]
Some file uploads use the worker container. can you also check if there are errors in there? `docker logs -f docker-canvas_worker_1`

There might be permissions issues with your `.data/tmp/` folder (where file uploads are stored). Can you check if there is something wrong there? 

You can also try changing the `- ./.data/tmp:/usr/src/app/tmp` volume from the compose file to `- data-tmp:/usr/src/app/tmp` and add the following to the end of the compose file.

```
volumes:
  data-tmp:
```

**Comment by thapakorn613** [comment]
I am done. 
I fix at `/usr/src/app/tmp` in docker container "docker-canvas_app_1" by `docker exec -it docker-canvas_app_1 bash`, change permission /tmp from root to docker.
well done. thank you.
