### ISSUE TITLE
dalay_job is not working 

### ISSUE THREAD

**Issue by thapakorn613** [ubc/docker-canvas#7]
jobs list is not working
.
https://drive.google.com/file/d/1-Lm2XWbWRY3dNWDqseD7e-kPzBszf87K/view?usp=sharing
.
Can help me?

**Comment by andrew-gardener** [comment]
I took a look at my job list (and the db) and there does seem to be a bunch of jobs listed. Didn't look with much detail but I know that jobs are running by looking at the worker logs and seeing activity.

I was able to match some of the job ids of the currently running jobs (listed as running forever?) with a few of the jobs in the current list but there are a lot of old jobs in that list as well. Don't know enough about delayed job and Canvas' implementation to know if there is an actual problem or not.

Do you have any error messages or know what kind of jobs aren't being processed?
